services:
  postgres:
    build:
      context: ./
      dockerfile: ./docker/postgresql/Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  adminer:
    build:
      context: ./
      dockerfile: ./docker/adminer/Dockerfile
    restart: always
    ports:
      - 8080:8080

