services:
  postgres:
    build:
      context: ./
      dockerfile: ./docker/postgresql/Dockerfile.prod
    env_file:
      - .env.prod
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
