FROM node:23-alpine

WORKDIR /app

COPY ./front .

RUN corepack enable pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

COPY ./front/dev.sh /dev.sh
RUN chmod +x /dev.sh

EXPOSE 3000

ENTRYPOINT ["/dev.sh"]