global:
  scrape_interval: 15s
  external_labels:
    monitor: "p10-backend"
    environment: "production"

scrape_configs:
  - job_name: "P10-backend"
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:4500"]
        labels:
          service: "P10-backend"
